variables:
  DOCKER_DRIVER: overlay
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

image: node:9.3

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: 
    - make prepare
    - make build

deploy-review:
  stage: deploy
  script:
    - echo "Deploy a review app"
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.fillip.pro
  only:
    - branches
  except:
    - master

deploy-staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.fillip.pro
  only:
  - master
  artifacts:
    paths:
    - public
  only:
  - master

deploy-release:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://fillip.pro
  artifacts:
    paths:
    - public
  when: manual
  only:
  - release

release-image:
  image: docker:latest
  stage: release
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_HUB_TOKEN -p $CI_BUILD_TOKEN https://registry-1.docker.io/
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE -f Dockerfile .
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_IMAGE:latest
    - docker push $CONTAINER_IMAGE:latest
  when: manual
  tags:
    - docker
  only: 
    - release