image: node:9.3

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: 
    - make prepare
    - make build

deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.fillip.pro
  only:
    - branches
  except:
    - master

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.fillip.pro
  only:
  - master
  artifacts:
    paths:
    - public
  only:
  - master

deploy_release:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://fillip.pro
  artifacts:
    paths:
    - public
  when: manual
  only:
  - release

