apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eostre-proxy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: eostre-proxy
    spec:
      containers:
        - name: eostre-proxy
          image: nginx:1.13.1
          ports:
            - containerPort: 443
              protocol: TCP
              name: https
            - containerPort: 80
              protocol: TCP
              name: http
          volumeMounts:
            - mountPath: /etc/nginx/ssl
              name: certs
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: nginx-config
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              name: nginx-config
      imagePullSecrets:
        - name: azure-secret
      volumes:
        - name: certs
          secret:
            secretName: nginx-cert
        - name: nginx-config
          configMap:
            name: nginx-config