apiVersion: v1
kind: Service
metadata:
  name: lehti-proxy
  labels:
    run: lehti-proxy
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  selector:
    run: lehti-proxy